create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  name_mr text,
  identifier text unique not null,
  role text not null default 'citizen' check (role in ('citizen', 'admin')),
  email text,
  mobile text,
  household_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.households (
  id text primary key,
  house_number text not null,
  head text not null,
  mobile text not null,
  members integer not null,
  ward text not null,
  address text not null,
  status text not null default 'Active'
);

alter table public.users drop constraint if exists users_household_id_fkey;
alter table public.users add constraint users_household_id_fkey foreign key (household_id) references public.households(id);

create table if not exists public.complaints (
  id text primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  citizen text not null,
  category text not null,
  title text not null,
  description text not null,
  location text,
  priority text not null default 'medium',
  status text not null default 'Pending',
  assigned_to text,
  remarks text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.applications (
  id text primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  purpose text not null,
  status text not null default 'Under Review',
  created_at timestamptz not null default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  body text not null,
  image_url text,
  status text not null default 'Draft',
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.users (id, name, identifier, email, mobile, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(coalesce(new.email, ''), '@', 1)),
    coalesce(new.raw_user_meta_data->>'identifier', new.email),
    new.email,
    new.raw_user_meta_data->>'mobile',
    'citizen'
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.users enable row level security;
alter table public.households enable row level security;
alter table public.complaints enable row level security;
alter table public.applications enable row level security;
alter table public.news enable row level security;

create policy "users read own profile" on public.users for select using (auth.uid() = id);
create policy "citizens read own complaints" on public.complaints for select using (auth.uid() = user_id);
create policy "citizens create own complaints" on public.complaints for insert with check (auth.uid() = user_id);
create policy "citizens read own applications" on public.applications for select using (auth.uid() = user_id);
create policy "citizens create own applications" on public.applications for insert with check (auth.uid() = user_id);
create policy "public read published news" on public.news for select using (status = 'Published');

-- Run this after creating the first admin Auth user, replacing the UUID.
-- update public.users set role = 'admin' where id = 'YOUR-AUTH-USER-UUID';

insert into public.households (id, house_number, head, mobile, members, ward, address)
values
  ('HH-2024-0142', '142', 'Rahul Patil', '98765-43210', 5, 'Ward 3', 'Shivaji Nagar, Rahatgaon'),
  ('HH-2024-0198', '198', 'Suresh Kumar', '97654-32100', 4, 'Ward 1', 'Gandhi Chowk, Rahatgaon'),
  ('HH-2024-0056', '56', 'Meena Devi', '99012-34567', 3, 'Ward 2', 'Ambedkar Nagar, Rahatgaon'),
  ('HH-2024-0312', '312', 'Anil Shinde', '98654-32100', 6, 'Ward 4', 'Bhima Colony, Rahatgaon')
on conflict (id) do nothing;

insert into public.news (title, category, body, status)
values
  ('Free Health Camp - 25 August 2024', 'Announcement', 'A free health camp will be organized at the Gram Panchayat office.', 'Published'),
  ('PM Awas Yojana Applications Now Open', 'Government Scheme', 'Eligible families can apply at the Panchayat office before 15 September 2024.', 'Published');
